# Import Conventions
import numpy as np  
import matplotlib.pyplot as plt  
import pandas as pd  
import seaborn as sns  
import statsmodels as sm

# NumPy
NumPy short for Numerical Python, is one of the most important foundational packages for numerical computing in Python.  
Many computational packages providing scientific functionality use NumPy’s array objects as one of the standard interface lingua francas for data exchange.

In [1]:
import numpy as np

## N-dimensional array
All of the elements must be the same type.

In [7]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

In [8]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [9]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [11]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [12]:
data.shape

(2, 3)

In [13]:
data.dtype

dtype('float64')

### Creating ndarray from a list.

In [14]:
data_list = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [16]:
arr = np.array(data_list)

In [19]:
arr.ndim

2

In [18]:
arr.shape

(2, 4)

In [20]:
arr.dtype

dtype('int64')

### Functions to create new arrays

In [23]:
np.zeros(3)

array([0., 0., 0.])

In [24]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
np.empty((2, 3, 2))

array([[[5.47383008e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [6.88460314e-310, 3.92738306e-033]],

       [[1.04876599e-042, 7.25341356e+169],
        [1.13827268e-042, 3.54162782e-061],
        [1.53324168e-075, 3.83623950e+175]]])

In [27]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [32]:
arr1.dtype

dtype('float64')

### Explicitly convert or cast an array from one data type to another using ndarray’s astype method

In [36]:
arr_int = np.array([1, 2, 3], dtype=np.int32)

In [40]:
arr_int.dtype

dtype('int32')

In [41]:
arr_float = arr_int.astype(np.float64)

In [42]:
arr_float.dtype

dtype('float64')

# Pandas

In [1]:
import numpy as np
import pandas as pd

### Series

In [4]:
obj = pd.Series([4, 5, -7, 3])
obj

0    4
1    5
2   -7
3    3
dtype: int64

In [13]:
obj[2]

np.int64(-7)

In [7]:
obj.array

<NumpyExtensionArray>
[np.int64(4), np.int64(5), np.int64(-7), np.int64(3)]
Length: 4, dtype: int64

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])

In [10]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [16]:
obj2['a']

np.int64(-5)

In [18]:

obj2[['d', 'b']]

d    4
b    7
dtype: int64

In [19]:
obj2[:2]

d    4
b    7
dtype: int64

In [22]:
obj >= 3

0     True
1     True
2    False
3     True
dtype: bool

In [21]:
obj2[obj2 >= 3]

d    4
b    7
c    3
dtype: int64

In [23]:
np.exp2(obj2)

d     16.00000
b    128.00000
a      0.03125
c      8.00000
dtype: float64

In [26]:
'b' in obj2

True

### Create Series from a dict

In [27]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

In [28]:
obj3 = pd.Series(sdata)

In [29]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [30]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

### Respecting a order

In [31]:
states = ["California", "Ohio", "Oregon", "Texas"]

In [32]:
obj4 = pd.Series(sdata, index=states)

In [33]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [35]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [36]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [38]:
obj4.notna()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [39]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [40]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

### Automatically aligns by index label in arithmetics operations

In [41]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [54]:
obj4.name = 'population_name'

In [55]:
obj4.index.name = 'states_index'

In [56]:
obj4

states_index
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population_name, dtype: float64

In [57]:
obj

0    4
1    5
2   -7
3    3
dtype: int64

In [64]:
obj.index = ['a', 'b', 'c', 'd']

In [65]:
obj

a    4
b    5
c   -7
d    3
dtype: int64

# DataFrame

In [66]:
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada","Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

In [67]:
frame = pd.DataFrame(data)

In [68]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

### Selecting and ordering

In [71]:
frame2 = pd.DataFrame(data, columns=['pop', 'year', 'asdf'])
frame2

   pop  year asdf
0  1.5  2000  NaN
1  1.7  2001  NaN
2  3.6  2002  NaN
3  2.4  2001  NaN
4  2.9  2002  NaN
5  3.2  2003  NaN

In [75]:
frame2.columns

Index(['pop', 'year', 'asdf'], dtype='object')

In [90]:
frame2['year']

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [91]:
frame2

   pop  year asdf
0  1.5  2000  NaN
1  1.7  2001  NaN
2  3.6  2002  NaN
3  2.4  2001  NaN
4  2.9  2002  NaN
5  3.2  2003  NaN

In [95]:
frame2.iloc[1]

pop      1.7
year    2001
asdf     NaN
Name: 1, dtype: object

In [96]:
frame2.asdf = 123

In [97]:
frame2

   pop  year  asdf
0  1.5  2000   123
1  1.7  2001   123
2  3.6  2002   123
3  2.4  2001   123
4  2.9  2002   123
5  3.2  2003   123

In [99]:

frame2.asdf = np.arange(6.)

In [100]:
frame2

   pop  year  asdf
0  1.5  2000   0.0
1  1.7  2001   1.0
2  3.6  2002   2.0
3  2.4  2001   3.0
4  2.9  2002   4.0
5  3.2  2003   5.0

In [101]:
frame2['date_choosed'] = frame2['year'] == 2002

In [102]:
frame2

   pop  year  asdf  date_choosed
0  1.5  2000   0.0         False
1  1.7  2001   1.0         False
2  3.6  2002   2.0          True
3  2.4  2001   3.0         False
4  2.9  2002   4.0          True
5  3.2  2003   5.0         False

In [104]:
del frame2['date_choosed']

In [105]:
frame2

   pop  year  asdf
0  1.5  2000   0.0
1  1.7  2001   1.0
2  3.6  2002   2.0
3  2.4  2001   3.0
4  2.9  2002   4.0
5  3.2  2003   5.0

### Dictinoary of dictionary

In [106]:
populations = {
    "Ohio": {
        2000: 1.5, 2001: 1.7, 2002: 3.6
    },
    "Nevada": {
        2001: 2.4, 2002: 2.9
    }}

In [108]:
frame3 = pd.DataFrame(populations)

In [109]:
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

### Swap rows and columns

In [110]:
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9